version: '2.1'
services:
  backend:
    image: bidgpt_backend
    depends_on:
      - embedding
    links:
      - embedding
    ports:
      - "8080:8080"
    environment:
      - API_KEY=
  embedding:
    image: embedding_model
    ports:
      - "80:80"
  frontend:
    image: gpt_ui
    ports:
      - "3000:80"
    depends_on:
      - backend
      - embedding
    links:
      - backend
